application: onlinepotentialflow
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /static
  static_dir: static

- url: /.*
  script: potentialflow.app

libraries:
- name: jinja2                                                      
  version: latest                                                      
- name: markupsafe                                             
  version: latest
- name: numpy
  version: latest
- name: matplotlib
  version: latest

